dnsutils/config.go, loggers/lokiclient.go
I experienced problems with newlines in the text-based logging. This motivated me to add a simple JSON mode to the Loki client.
=> Add JSON mode to Loki client

dnsutils/dns.go, dnsutils/dns_test.go
Fixes slice bounds out of range panic when parsing invalid DNS packet containing only first byte of label pointer. 
Add unit test verifying that invalid label pointer is now detected and error is returned when it is being parsed.
=> Add missing length check when reading label pointer

dnsutils/edns.go, dnsutils/edns_test.go
* Fixes panics caused by invalid packets, improved bounds checks for EDNS options parsing. 
* `DecodeEDNS()` will now return error if more than one OPT RR is encountered. 
* Added multiple unit tests to cover EDNS parsing.
=> Improved bounds checks for EDNS decoding

dnsutils/dns.go, dnsutils/dns_test.go, dnsutils/edns_test.go, subprocessors/decoder.go, subprocessors/decoder_test.go, subprocessors/dnsreader.go, subprocessors/dnstapreader.go
* Move common part of DNS packet decoding from `dnsreader` and `dnstapreader` into new `decodePayload()` function which can be used by both readers. 
* Add unit tests for payload decoding.
* Change `decodeQuestion()` to take the number of questions on packet as parameter and handle multiple questions on single DNS packet.
* Multiple queries in single packet are supported by the specification, but in practise DNS servers rarely support them (see, for example [this answer from stack overflow](https://stackoverflow.com/questions/4082081/requesting-a-and-aaaa-records-in-single-dns-query/4083071#4083071l)) and thus we should not see them in wire. 
* Changed the `decodeQuestion()` to handle multiple questions by just returning `qname` and `qtype` from the last question. This obviously does not …
=> A bit of refactoring for DNS packet decoding

dnscollector.go
tcpclient logger loads the default configuration instead of the user.
=> tcpclient logger configuration fix

.github/workflows/benchmark.yml, .github/workflows/build.yml, .github/workflows/code.yml, .github/workflows/publish.yml, .github/workflows/releaser.yml, .github/workflows/testing-dnstap.yml, .github/workflows/testing-go.yml, .github/workflows/testing-powerdns.yml
PR to fix the following warning in GH actions:
`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/setup-go, actions/checkout`
`The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`
`The python-version input is not set. The version of Python currently in `PATH` will be used.`
=> GH actions: some actions are deprecated.

config.yml, dnsutils/config.go, doc/configuration.md, testsdata/filtering_keep_domains.txt, testsdata/filtering_keep_domains_regex.txt, transformers/filtering.go, transformers/filtering_test.go
This PR adds a filter for "keep domains", where all except specified domains are dropped. 
This functionally works exactly the opposite of the existing dropDomains filters for fqdns and domain regexes. With the existing `dropDomains` filter, all domains are kept *except* those that are listed in the `DropDomainFile` or `DropFqdnFile`: with this new `keepDomains` filter, all domains are *dropped* except for those that are listed in the `KeepDomainFile` or the `KeepFqdnFile`.
=> Add filtering option to keep only certain domain records.

loggers/prometheus.go
This basically duplicates the NXDOMAIN metrics logic.
=> Prometheus: Add SERVFAIL metrics

config.yml, dnsutils/config.go, doc/loggers.md, loggers/syslog.go
On syslog logger it is useful to set which syslog format we want between unix (default one), [rfc3164](https://www.rfc-editor.org/rfc/rfc3164) and [rfc5424](https://www.rfc-editor.org/rfc/rfc5424).
This PR add to syslog config parameter to syslog which accept rfc3164 and rfc5424 as value and set the syslog formatter linked to this format.
=> Add syslog format

collectors/sniffer_afpacket.go
I ran into an issue on some of my DNS servers where go-dnscollector would panic either immediately or not long after starting with the message
```
panic: interrupted system call
```
It seems that the go syscall package does not natively retry after receiving EINTR on Recvmsg and passes it back to the application to handle See [this change](https://go-review.googlesource.com/c/go/+/232862) for examples.
This pull request is to handle this scenario and continue processing after EINTR rather than panicking.
=> Added handling for EINTR on syscall.Recvmsg

doc/logger_prometheus.md
This was not documented and I had to read the code like a caveman to figure out how to disable basic auth :wink:
=> docs: Document basic-auth-enable for Prometheus logger

dnscollector.go
This PR adds truly simple config validation. It allows for go-dnscollector to parse the configuration and stops right before actually launching the collectors/transformers/outputs.
The program can still fail after someone has validated their config, like permission errors for the dnstap socket or ports already in use. But this should at least let the user know if the config is valid.
=> Add basic config validation

.gitignore, dnsutils/dns.go, dnsutils/dns_test.go, doc/dnsparser.md, go.sum
This PR adds support for parsing SVCB and HTTPS records.
It also contains some tests and I have run some end-to-end tests and it seems to work, but I recommend a healthy dose of reviews before merging.
I've also added a small commit that ignores the built binary in git.
- chore: ignore the built binary
- feat: Add SVCB and HTTPS parsing
=> Add parsing for SVCB and HTTPS

config.yml, dnsutils/config.go, dnsutils/message.go, doc/transformers.md, example-config/use-case-20.yml, transformers/reducer.go, transformers/reducer_test.go
This PR add the following new settings
- a new directive to get cumulative length of  each queries or replies
- new qname+1 criteria
=> Transform Reducer: add cumulative length and more options

config.yml, dnsutils/config.go, docs/loggers/logger_elasticsearch.md, loggers/elasticsearch.go, loggers/elasticsearch_test.go
This PR is introducing bulk requests for the ES logger, introducing a new parameter called `bulk-size` and splits the previous `url` parameter in `server` and `index`.
Additionally, a new parameter (`flush-interval`) is introduced, to flush the ES buffer on a defined period.
=> Refactor ES logger for bulk requests

loggers/elasticsearch.go, loggers/elasticsearch_test.go
Since 0.35 indexing to elasticsearch does no longer work if the destination is a Data Stream.
This is because Data Streams only allow "create" (https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html)
This pull request changes the "index" to a "create" op_type which allows sending logs to a Data Stream again. 
"index" should not be needed as we never update existing documents.
=> elasticsearch logger: change op_type to create to allow sending to Data Streams

.github/workflows/build.yml, .goreleaser.yml, collectors/sniffer_afpacket.go, collectors/sniffer_afpacket_freebsd.go, collectors/tzsp_freebsd.go
This PR allows building the DNS Collector for FreeBSD. This build disables the AF_PACKET and tzsp sniffers for such builds.
=> Support building for FreeBSD

loggers/redispub.go
=> chg: [redispub] reading redis responses

.goreleaser.yml, Makefile, dnscollector.go, docs/metrics.txt, loggers/prometheus.go, loggers/prometheus_test.go, loggers/restapi.go, loggers/restapi_test.go, loggers/statsd.go, loggers/statsd_test.go
pull request for #276 
The new build_info metric:
`dnscollector_build_info{branch="main",goarch="amd64",goos="linux",goversion="go1.21.3",revision="9fde998",tags="unknown",version="0.37.0-beta1"} 1`
=> Use prometheus/version lib, change on build_info metric

loggers/tcpclient.go
tcpclient logger was referring to FluentD configuration options.  This commit amends to use TcpClient options, as intended.
Resolves #450
=> Update tcpclient logger to use flush interval

config.yml, dnsutils/config.go, dnsutils/message.go, docs/collectors/collector_dnstap.md, loggers/stdout.go, loggers/stdout_test.go, processors/dnstap.go, processors/dnstap_test.go
This PR add the `disable-dnsparser` setting to disable the embedded DNS parser
=> dnstap collector: new settings to disable dnsparser

config.yml, dnsutils/constants.go, processors/powerdns.go, processors/powerdns_test.go
go/dnsmessage has been replaced by miekg/dns to avoid empty DNS payload with long domain name
=> powerdns collector: replace go/dnsmessage by miekg/dns

config.yml, docs/_examples/use-case-12.yml, docs/_examples/use-case-16.yml, docs/_examples/use-case-5.yml, docs/loggers/logger_dnstap.md, pkgconfig/loggers.go
The `dnstap` logger is renamed to `dnstapclient`.
The YAML name of each loggers or collectors must be uniq to support the future `pipeline` mode.
=> Rename dnstap logger (breaking changes)

config.yml, dnsutils/constant.go, docs/loggers/logger_prometheus.md, docs/metrics.txt, go.mod, go.sum, loggers/prometheus.go, loggers/prometheus_test.go, pkgconfig/loggers.go
This PR try to find a solution to limit memory usage with Prometheus logger.
The following list are stored in memory without any limitations:
- queries number made by a specific requestor
- queries number ended up in NOERROR (or other except NXDOMAIN and SERVFAIL)
- queries number ended up in NXDOMAIN
- queries number ended up in SERVFAIL
- queries number for a specific TLD
- queries number for a specific eTLD+1
=> prometheus logger: fix potential unlimited memory usage

pkgconfig/collectors.go
This patch fixes the issue reported on https://github.com/dmachard/go-dnscollector/issues/516#issuecomment-1892754164
=> fix bad yaml key for dnstap-relay collector 

dnsutils/message.go, dnsutils/message_test.go, processors/dnstap.go
This PR add the support of DNSTap extra field for the DNSTap logger as reported in  https://github.com/dmachard/go-dnscollector/issues/516
Only string values are supported.
=> Support of DNSTap extra field on outgoing messages

README.md, loggers/fluentd.go, loggers/kafkaproducer.go, loggers/redispub.go, loggers/tcpclient.go, loggers/tcpclient_test.go
fix to avoid a situation where the buffer is not flushed as expected, only in specific conditions (slow traffic lower than the maximum buffer size and re-connection attempt) 
#536
=> kafka, redis, fluentd and tcpclient loggers: no flush occurred on specific conditions for on connection attempts

loggers/syslog.go
=> syslog logger - fix protocol wrong type for unix socket

README.md, config.yml, dnsutils/message.go, dnsutils/message_test.go, docs/configuration.md, docs/dnsjson.md, processors/dnstap.go
=> dnstap collector: decode query zone field

.github/workflows/bench-go.yml, README.md, config.yml, dnsutils/message.go, dnsutils/message_test.go, docs/transformers/transform_normalize.md, transformers/normalize.go, transformers/normalize_test.go
=> normalize transformer:  add icann managed flag in dnsmessage & new bench tests

.github/workflows/bench-go.yml, .github/workflows/build.yml, .github/workflows/golint.yml, .github/workflows/goreleaser.yml, .github/workflows/testing-dnstap.yml, .github/workflows/testing-go.yml, .github/workflows/testing-powerdns.yml, Dockerfile, Makefile, README.md, go.mod
=> add go1.22 support

pkgutils/configchecker.go, pkgutils/configchecker_test.go
=> fix relabel-config error in loki client

docs/loggers/logger_kafka.md, loggers/kafkaproducer.go, pkgconfig/loggers.go
=> Fix kafka - add missing textformat setting

Makefile, workers/syslog.go
=> update makefile deps

README.md, docs/collectors/collector_dnsmessage.md, docs/workers.md, workers/dnsmessage_test.go
=> dnsmessage collector: add missing docs and tests

README.md, config.yml, dnsutils/message.go, dnsutils/message_test.go, docs/development.md, docs/dnsjson.md, docs/transformers.md, docs/transformers/transform_relabeling.md, docs/transformers/transform_rewrite.md, pkgconfig/transformers.go, transformers/rewrite.go, transformers/rewrite_test.go, transformers/transformers.go
This PR implements #527
Config example
```yaml
- name: tap
dnstap:
listen-ip: 0.0.0.0
listen-port: 6000
transforms:
rewrite:
identifiers:
dnstap.version: ""
dnstap.identity: "foo"
```
=> add rewrite transform + quote some text directives

workers/kafkaproducer.go
properly applied round robin #800
=> kafka: apply round robin on  bach

workers/sniffer_afpacket_linux.go
=> afpacket sniffer: fix deadlock on stop

workers/logfile.go
This PR improves performance - related to #837
=> file logger: compressing is no more blocking

dnsutils/dns_parser.go
The dns record type `52` was wrong: `TSLA` instead of `TLSA`.
=> Fix TLSA typo

docs/_integration/elasticsearch/README.md, docs/_integration/elasticsearch/config.yml, docs/_integration/elasticsearch/docker-compose.yml, docs/loggers/logger_elasticsearch.md, pkgconfig/loggers.go, workers/elasticsearch.go, workers/elasticsearch_test.go
=> Added ElasticSearch API basic authentication

docs/loggers/logger_kafka.md, workers/kafkaproducer.go
fix #679 
Adding multiple Kafka brokers for initial cluster metadata exchange is critical for high availability. Accordingly, the modifications to the Kafka producer code will allow the administrator to specify multiple brokers from the config.yml file:
```yml
- name: kafka
kafkaproducer:
remote-address: broker1.net,broker2.net,broker3.net,....
remote-port: 9092
...
```
=> Adding support for multiple Kafka brokers for dial process

README.md, dnsutils/dnsmessage_text.go, dnsutils/dnsmessage_text_test.go, docs/dnsconversions.md
fix #960 
new text directive added: `anwer-ips`
=> feat: log all answers IP in text format log

docs/_integration/kafka/config.yml, docs/loggers/logger_kafka.md, pkgconfig/loggers.go, workers/kafkaproducer.go, workers/kafkaproducer_test.go
=> fix(#975): rename buffer-size to batch-size in Kafka logger config

docs/loggers/logger_kafka.md, pkgconfig/loggers.go, workers/kafkaproducer.go
The readyTimer in the Kafka producer code was responsible for <a href="https://github.com/dmachard/DNS-collector/blob/5d254809173febecd4f84699e1b005c67a6b73e9/workers/kafkaproducer.go#L372">cancelling</a> Kafka after 10 seconds of unreachability to all the provided brokers. Therefore, I have added a new configuration parameter _cancel-kafka_ to the yaml configuration file
=> Fixing kafka worker get cancelled after 10 seconds of broker unreachability.

dnsutils/dns_parser.go, dnsutils/dns_parser_payload_test.go
This PR updates the DNS decoding to use the "real" RCode. I noticed that a BADCOOKIE response (RCode 23) was sent as `dns.rcode = XYRRSET` (7) and `edns.rcode = 16` and 16 + 7 = 23. With this change, `dns.rcode` is now set to `BADCOOKIE`.
Discussion:
* Is `dns.rcode` the right place? If not, would something like `dns.effective-rcode` need to be created?
* What to do with `edns.rcode`?
* Should this remain a number?
* Should this contain the "effective" RCode when there is an extended RCode?
* Should the effective RCode be done by a transformer and not the parser?
To Do:
=> feat: Decode RCode to the real RCode in case of Extended Errors

dnsutils/dnsmessage.go, docs/collectors/collector_webhook.md, docs/transformers.md, docs/transformers/transform_rest.md, docs/workers.md, pkgconfig/collectors.go, pkgconfig/transformers.go, pkginit/pipelines.go, transformers/rest.go, transformers/rest_test.go, transformers/transformers.go, workers/webhook.go, workers/webhook_test.go
I've added two experimental ways to do HTTP lookups to 3rd party system and add HTTP response into dnsmessage to be processed further.
I first added REST transformer and while it works fine, it's not very performant as the messages are processed in single thread and HTTP lookups take quite a bit of time.
I then added webhook "middleware" (it's neither collector or logger, similar to dnsmessage) that can be used as part of pipeline. It can use >1 threads so performance is greatly improved. Obvious downside is that message order cannot be guaranteed and that is why default number of threads is 1.
Should I keep both or drop the transformer?
Does this look mergeable? If so I'll finish and add tests/documentation as well.
=> Added experimental HTTP enrichment

dnsutils/dnsmessage.go, dnsutils/dnsmessage_text.go, dnsutils/dnsmessage_text_test.go, docs/collectors/collector_powerdns.md, workers/powerdns.go
fix #1072 
```
dnsmessage_json_test.go:162: json format different from reference, Get=map[applied-policy:basicrpz applied-policy-hit:hit applied-policy-kind:kind applied-policy-trigger:trigger applied-policy-type:type device-id:ffffffffffffffffeaaeaeae device-name:foobar edns-version: http-version:http3 initial-requestor-id:5e006236c8a74f7eafc6af126e6d0689 message-id:27c3e94ad6284eec9a50cfc5bd7384d6 metadata:map[stream_id:collector] opentelemetry-data: original-request-subnet:subnet requestor-id:f7c3e94ad6284eec9a50cfc5bd7384d6 tags:[tag1]] Want=map[applied-policy:basicrpz applied-policy-hit:hit applied-policy-kind:kind applied-policy-trigger:trigger applied-policy-type:type device-id:ffffffffffffffffeaaeaeae device-name:foobar http-version:http3 …
```
=> feat: add OpenTelemetry data and EDNS version to PowerDNS collector
