dmachard/DNS-collector

dnsutils/message.go, doc/dnsjson.md, subprocessors/powerdns.go
Adds PowerDNS tags to json output as discussed here #68
=> Add PowerDNS tags

transformers/subprocessors.go, transformers/subprocessors_test.go
Introduces a change to Transforms subprocessor where only active transformations are applied to each message. Also introduces tests to make sure the Transform subprocessor applies transformations to dns messages and that this is interoperable with filters.
=> Active transforms

README.md, doc/loggers.md
Just a pull request to update the documentation
=> Docs improvements

collectors/file_ingestor.go
=> ingestor: support compressed pcap file

config.yml, dnsutils/config.go, dnsutils/message.go, doc/configuration.md, doc/transformers.md, transformers/extract.go, transformers/extract_test.go, transformers/subprocessors.go
This PR adds the ability to have the base64 encoded payload in logger's  text-format output.
=> adds: [logger] raw DNS response

README.md, config.yml, dashboards/grafana_prometheus.json, dnsutils/config.go, doc/logger_loki.md, doc/logger_prometheus.md, doc/metrics.txt, loggers/prometheus.go, loggers/prometheus_test.go
breaking changes in metrics to support high load
=> prometheus logger redesign to support high load

README.md, config.yml, dnsutils/config.go, dnsutils/message.go, doc/transformers.md, example-config/use-case-22.yml, transformers/machinelearning.go, transformers/subprocessors.go
This PR add a new transform, witch will add new directives for machine learning purpose.
=> New transform to add features for machine learning

collectors/dnstap_processor.go, config.yml, dnsutils/message.go, dnsutils/message_test.go, docs/configuration.md, docs/dnsjson.md
This PR add the support for dnstap metadata (extra field)
- JSON is updated with a new key `extra` in dnstap section.
- a new default text directive added
=> dnstap extra field support

transformers/normalize.go
=> publicsuffix transform: improve logging

config.yml, dnsutils/config.go, dnsutils/constants.go, docs/loggers/logger_kafka.md, loggers/kafkaproducer.go, loggers/kafkaproducer_test.go
This PR implemented compression for #481
=> feat: add compression support for kafka logger

Dockerfile
Reduce number of RUN in Dockerfile
=> Optimize docker image for #470

loggers/prometheus.go, loggers/prometheus_test.go
=> logger prometheus: fix panic error with invalid qname 

dnsutils/message.go, transformers/latency.go, transformers/latency_test.go
=> fix latency when quiet-text is enabled

loggers/syslog.go
=> fix crash when syslog refused connections

Makefile, loggers/fakelogger.go, processors/constants.go, processors/dns.go, processors/dns_test.go, processors/dnstap.go, processors/dnstap_test.go, processors/powerdns.go, processors/powerdns_test.go
=> fix to avoid deadlock situations in multiplexer mode - regression

pkgconfig/config.go, pkgconfig/config_test.go
=> fix to detect invalid logger type in config

dnsutils/message.go, dnsutils/message_test.go
=> Expose dns id in json model

dnsutils/dns_parser.go, dnsutils/message.go, dnsutils/message_test.go, docs/dnsjson.md
=> json model: add missing rd and cd flags

dnsutils/message.go, docs/collectors/collector_powerdns.md, processors/powerdns.go
=> Add RPZ policy details with powerdns protobuf

docs/_examples/use-case-1.pipeline.yml, docs/_examples/use-case-10.pipeline.yml, docs/_examples/use-case-11.pipeline.yml, docs/_examples/use-case-11.yml, docs/_examples/use-case-12.pipeline.yml, docs/_examples/use-case-13.pipeline.yml, docs/_examples/use-case-14.pipeline.yml, docs/_examples/use-case-15.pipeline.yml, docs/_examples/use-case-16.pipeline.yml, docs/_examples/use-case-17.pipeline.yml, docs/_examples/use-case-18.pipeline.yml, docs/_examples/use-case-19.pipeline.yml, docs/_examples/use-case-2.pipeline.yml, docs/_examples/use-case-20.pipeline.yml, docs/_examples/use-case-20.yml, docs/_examples/use-case-21.pipeline.yml, docs/_examples/use-case-22.pipeline.yml, docs/_examples/use-case-22.yml, docs/_examples/use-case-23.pipeline.yml, docs/_examples/use-case-24.pipeline.yml, docs/_examples/use-case-3.pipeline.yml, docs/_examples/use-case-4.pipeline.yml, docs/_examples/use-case-5.pipeline.yml, docs/_examples/use-case-6.pipeline.yml, docs/_examples/use-case-7.pipeline.yml, docs/_examples/use-case-8.pipeline.yml, docs/_examples/use-case-9.pipeline.yml, docs/_examples/use-case-9.yml, pkglinker/pipelines.go
=> add tests for pipeline mode

README.md, config.yml, dnsutils/dns_parser.go, dnsutils/dns_parser_test.go, dnsutils/edns_parser_test.go, dnsutils/message.go, dnsutils/message_test.go, docs/configuration.md, docs/dnsjson.md, processors/powerdns.go
=> decode dns class properly

pkgconfig/loggers.go
This was forgotten in the original PR.
=> Add Scalyr defaults

config.yml, dnscollector.go, docs/configuration.md, pkgconfig/global.go, pkgconfig/global_test.go
PR to implemented feature request #722
=> add pid file support

README.md, config.yml, docs/loggers/logger_file.md, docs/workers.md, pkgconfig/config_test.go, pkgconfig/pipelines.go
=> fix config checker

README.md, docs/_integration/elasticsearch/config.yml, docs/_integration/elasticsearch/docker-compose.yml, docs/_integration/fluentd/config.yml, docs/_integration/fluentd/docker-compose.yml, docs/_integration/influxdb/README.md, docs/_integration/influxdb/config.yml, docs/_integration/influxdb/docker-compose.yml, docs/_integration/kafka/docker-compose.yml, docs/_integration/loki/README.md, docs/_integration/loki/config.yml, docs/_integration/loki/datasource.yml, docs/_integration/loki/docker-compose.yml, docs/_integration/loki/grafana.ini, docs/_integration/loki/loki-config.yaml, docs/_integration/prometheus/README.md, docs/_integration/prometheus/config.yml, docs/_integration/prometheus/docker-compose.yml, docs/_integration/prometheus/prometheus.yml, docs/loggers/logger_prometheus.md
=> add integration examples

README.md, docs/configuration.md, docs/transformers/transform_geoip.md, pkgconfig/transformers.go, transformers/geoip.go, transformers/geoip_test.go
=> add ecs support on geoip

dnscollector.go, workers/worker.go
=> stop collect before monitor on worker

docs/dashboards/grafana_prometheus.json, workers/prometheus.go
=> prometheus logger: add new counter for dns messages operations

docs/loggers/logger_file.md, pkgconfig/loggers.go, workers/logfile.go
=> file logger: no more block postrotate command

.goreleaser.yml
=> Update .goreleaser.yml 

telemetry/prometheus.go
=> fix: prevent multiple channel close in Telemetry  Stop method

README.md, dnsutils/dnsmessage_matching.go, docs/transformers/transform_newdomaintracker.md, docs/transformers/transform_trafficreducer.md, pkgconfig/transformers.go, transformers/reducer.go, transformers/reducer_test.go
=> feat(transformer): add configurable unique fields to traffic reducer

README.md, dnsutils/dnsmessage.go, dnsutils/dnsmessage_json_test.go, dnsutils/dnsmessage_text.go, dnsutils/dnsmessage_text_test.go, docs/collectors/collector_powerdns.md, workers/powerdns.go
=> feat(powerdns): add hex value for MessageId and InitialRequestorId

README.md, docs/transformers/transform_reordering.md, pkgconfig/transformers.go, transformers/reordering.go, transformers/reordering_test.go, transformers/transformers.go
=> feat(transformer): new reordering transform to sort logs by timestamp

.goreleaser.yml
=> fix deprecated message in goreleaser #930

.github/workflows/bench-go.yml, .github/workflows/build.yml, .github/workflows/golint.yml, .github/workflows/goreleaser.yml, .github/workflows/publish.yml, .github/workflows/testing-dnstap.yml, .github/workflows/testing-go.yml, .github/workflows/testing-powerdns.yml, .golangci.yml, Makefile, dnsutils/dnsmessage_text.go, dnsutils/edns_parser.go, dnsutils/helper.go, docs/development.md, workers/file_ingestor.go, workers/sniffer_afpacket_linux.go, workers/statsd.go
=> build: add go1.24 support on CI

.github/workflows/testing-dnstap.yml, .github/workflows/testing-powerdns.yml, tests/dnsquery_dnstaptcp.py, tests/testsdata/powerdns/dnsdist2_doq.yml, tests/testsdata/powerdns/dnsdist2_protobuf.yml, tests/testsdata/powerdns/dnsdist2_tcp.yml
=> build(ci): add dnsdist2 on dnstap tests

README.md, dnsutils/dnsmessage.go, dnsutils/dnsmessage_json_test.go, dnsutils/dnsmessage_text.go, dnsutils/dnsmessage_text_test.go, docs/dnsconversions.md, workers/dnstapserver.go
=> feat: add support to get http-protocol from dnstap

.github/workflows/testing-dnstap.yml, README.md, tests/testsdata/bind/bind9_unix.conf
=> feat(ci): add bind9 in automated dnstap test

.github/workflows/bench-go.yml, .github/workflows/build.yml, .github/workflows/publish.yml, .github/workflows/testing-go.yml, Makefile, README.md, docs/development.md, go.mod
=> feat: minimum go version updated to 1.24 and improve makefile
